[package]
name = "utxo-discovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kv = "0.24.0"
rand = "0.8.5"
rand_distr = "0.4"
rsa = "0.9.6"
sha256 = "1.5.0"
